// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MusicNoteGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("note")]
        public string Note { get; set; }

        [JsonProperty("octave")]
        public long Octave { get; set; }

        [JsonProperty("frequency")]
        public double Frequency { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("audio")]
        public Audio Audio { get; set; }
    }

    public partial class Audio
    {
        [JsonProperty("audioFile")]
        public string AudioFile { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }

        [JsonProperty("sampleRate")]
        public string SampleRate { get; set; }

        [JsonProperty("bitDepth")]
        public string BitDepth { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }
    }
}
